### ISSUE TITLE
Import error - scipy version 1.8.0 

### ISSUE THREAD

**Issue by lebckr** [jjhelmus/nmrglue#171]
Importing nmrglue with: 

`import nmrglue as ng`

leads to:

`File "/home/*/anaconda3/envs/*/lib/python3.10/site-packages/nmrglue-0.8-py3.10.egg/nmrglue/analysis/leastsqbound.py", line 7, in <module>`
   ` from scipy.optimize.minpack import _check_func`
`ImportError: cannot import name '_check_func' from 'scipy.optimize.minpack' (/home/*/anaconda3/envs/*/lib/python3.10/site-packages/scipy/optimize/minpack.py)`

Downgrading scipy from 1.8.0 to 1.7.3 solves this issue, this is probably just a naming issue.

Thank you!

**Comment by kaustubhmote** [comment]
This is fixed by #167. The newest version of nmrglue that was released today on PyPI (v0.9) has the fix. So if you reinstall nmrglue, it should  work with scipy v1.8 as well.
